services:
  php:
    command: composer ${COMPOSER_COMMAND:-test}
    working_dir: /app
    build:
      context: "./container/php${PHP_VERSION:?PHP_VERSION}"
      dockerfile: Containerfile
    environment:
      XDEBUG_MODE: coverage
      PHP_VERSION: "${PHP_VERSION:?PHP_VERSION}"
      COMPOSER_COMMAND: "${COMPOSER_COMMAND:-test}"

    volumes:
      - .:/app:rw
      - $PWD/docker/php${PHP_VERSION:?PHP_VERSION}/.composer/cache:/root/.composer/cache:rw
      - $PWD/docker/php${PHP_VERSION:?PHP_VERSION}/composer.lock:/app/composer.lock:rw
      - $PWD/docker/php${PHP_VERSION:?PHP_VERSION}/vendor:/app/vendor:rw
