x-common: &common
  working_dir: /app
  volumes:
    - ".:/app"
  command: composer test

services:

  php74:
    build: ./docker/php74
    <<: *common

  php81:
    build: ./docker/php81
    <<: *common

  php82:
    build: ./docker/php82
    <<: *common

  php83:
    build: ./docker/php83
    <<: *common

  php84:
    build: ./docker/php84
    <<: *common
